(^_^)
college-VIVT/StudentWork_FindWord pull request #1
Opened 2020-11-29 16:21 UTC by FoxRed-cmd

2020-12-02 07:29 UTC, anst-foto commented
> Я сделал, возможно не всё понял, что требовалось и ещё у меня есть ряд проблем.
> Во-первых, как я понял, если метод выполняется асинхронно, то он никак не влияет на форму, но в момент выполнения она у меня всё равно виснет, к тому же, во время написания кода выскакивало исключение из-за того, что я изменяю переменные, объявленные в другом потоке.
> Я гуглил и нашёл как это обходить здесь: (https://www.youtube.com/watch?v=vHqHrf914TA).
> Но даже сделав так окно у меня всё равно виснет во время выполнения.
> А ещё я не придумал, как вывести информацию, если слово встречается в двух и более файлов, поэтому если такое происходит совпадение, то он выводит его каждый раз.
> Ещё я не придумал, как смотреть поддиректории поддиректорий. Например, если мы ищем на рабочем столе и там есть папка, то он её посмотрит, но если в папке есть ещё папка, то дальше он не залезет. Я пытался сначала получить в список пути абсолютно всех папок и подпапок, которые могут быть, но запутался в циклах и у меня ничего не вышло. Например, у меня было исключение, что какая-то папка отказала в доступе или что-то вроде того, поэтому оставил как есть.

Исключения нужно обрабатывать. Посмотри вот сей материал - https://metanit.com/sharp/tutorial/2.14.php

Есть задача - её нужно решить. И не надо опускать руки, если что-то не получается.

Зачем изменять в асинхронном методе переменные другого потока? Не проще возвращать значение. Ведь лучше дождаться выполнения асинхронного метода и потом поработать с результатами.

2020-12-03 18:22 UTC, FoxRed-cmd commented
![image](https://user-images.githubusercontent.com/71372800/101066945-fb7cc200-35a7-11eb-9b69-ae32156a2f02.png)
![image](https://user-images.githubusercontent.com/71372800/101071064-287fa380-35ad-11eb-8cc7-1199ae1d7204.png)

Вот такая у меня была ошибка. И по-моему это из-за режима отладки. Но я не уверен, в любом случае асинхронно у меня не выполняется. Я знаю, что исключения нужно обрабатывать, в коде имеются конструкции try catch, но не думаю, что имеет смысл обрабатывать именно это исключение. Фактически у меня всё работает. Поиск слова в файле по указанию пути к файлу работает. Поиск слова в файлах по указанию пути директории работает. Нашёл как получить список всех файлов в указанной вот: (files_str = Directory.GetFiles(path, "*.*",SearchOption.AllDirectories);). Теперь ищет везде. Но проблема с повисанием не уходит, я не знаю, что я не так делаю, я уже пробовал и асинхронно и с помощью Thread. Кроме как добавить Action и Invoke, я больше не не нашёл ничего. Да, исключение больше не появляется, но форма всё равно виснет.

2020-12-05 09:43 UTC, anst-foto commented
А где библиотека для поиска слов???

2020-12-05 09:45 UTC, anst-foto requested changes
А где библиотека, которая должна использоваться в обеих проектах?

2020-12-05 09:53 UTC, FoxRed-cmd commented
Ааа, нужно было одну библиотеку на два проекта. Я этого просто не понял. Сделаю. А нужно получается сделать два класса в библиотеке, которым будет передаваться слово и путь, или имеется ввиду что-то другое?

2020-12-05 09:59 UTC, anst-foto commented
> Ааа, нужно было одну библиотеку на два проекта. Я этого просто не понял. Сделаю. А нужно получается сделать два класса в библиотеке, которым будет передаваться слово и путь, или имеется ввиду что-то другое?

Как сделаешь: один или два класса

2020-12-06 16:15 UTC, FoxRed-cmd commented
Здравствуйте. Теперь я сделал всё как надо. Обидно, что я сразу не понял, что нужно отдельную библиотеку делать. Через класс получилось на много легче, теперь и асинхронный метод работает, и вывод я смог реализовать нормально.

2020-12-06 20:56 UTC, FoxRed-cmd commented
Ещё мне не нравиться, что хоть форма и не зависает теперь, но не понятно ищет она или нет, так что я добавил вторую форму, которая отображает Поиск... на то время пока он идёт, а потом закрывается. Хотел сначала прогресс баром, но не додумался как с ним можно сделать.

2020-12-07 07:39 UTC, anst-foto reviewed
Отлично!

2022-06-09 08:44 UTC, closed without merging